import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import { StoreProvider } from "./store/user-store/store-provider";
import {store} from './store/index';
import { fetchUser } from "./store/user-store";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    
 
  await  store.dispatch(fetchUser());
  const {user} = store.getState().user;
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider preloadedState={{
          user: {
            user,
          }
        }}>
        <Header />
        <main>{children}</main>
        </StoreProvider>
      </body>
    </html>
  );
}
